### ISSUE TITLE
Remove "test pages"

### ISSUE THREAD

**Issue by sidehackcreative** [Luftgekuhlt-com/luft#8]
Luft 3 (can't change name, blocking Past event page setup)
Galleries
Builds
Past Events
Test Page

**Comment by cvollmer** [comment]
@sidehackcreative - I made it so when you archive a page it appends "-archived" to the existing slug so it can be used again. if you ever want to unarchive the page you will have to deal with renaming the slug and any conflicts that might exists since it was archived. you can archive a page by editing the page and then there is a big red button.
